"use client";
import type { QuestionCandidate } from "@/lib/types";

export function QuestionCard({
  question,
}: {
  question: QuestionCandidate;
}) {
  return (
    <section className="rounded-lg border border-[var(--border)] bg-white p-5">
      <header className="mb-3 flex items-start justify-between gap-3">
        <div>
          <span className="rounded bg-blue-50 px-2 py-0.5 text-xs font-semibold text-[var(--blue)]">
            {question.max_marks} marks
          </span>
          <span className="ml-2 text-xs text-[var(--text-secondary)]">
            {question.paper_ref}
          </span>
        </div>
      </header>
      <div className="whitespace-pre-wrap text-base">
        {question.question_text}
      </div>
      {question.used_generated_mark_scheme && (
        <p className="mt-3 text-xs text-[var(--text-secondary)]">
          Note: mark scheme generated by Alex (real mark scheme not found)
        </p>
      )}
    </section>
  );
}
